animations {
    enabled = yes

    # Более агрессивные кривые для ощущения скорости
    bezier = myBezier, 0.05, 0.9, 0.1, 1.05
    bezier = fluent, 0.4, 0, 0.2, 1

    # Настройки (Скорость ниже = анимация быстрее)
    animation = windows, 1, 3, myBezier          # Быстрое открытие окон
    animation = windowsOut, 1, 3, default, popin 80%
    animation = border, 1, 5, default
    animation = fade, 1, 3, default
    animation = workspaces, 1, 2.5, fluent, slide # Быстрое переключение рабочих столов
    animation = layers, 1, 3, fluent, fade        # Слои (Waybar, Rofi) открываются мгновенно
}
